--liquibase formatted sql

--changeset owengc:002
CREATE TABLE teams (
    year_id INTEGER NOT NULL,
    league_id VARCHAR(5),
    team_id VARCHAR(3) NOT NULL,
    franch_id VARCHAR(3),
    div_id CHAR(1),
    rank INTEGER,
    g INTEGER,
    g_home INTEGER,
    w INTEGER,
    l INTEGER,
    div_win CHAR(1),
    wc_win CHAR(1),
    lg_win CHAR(1),
    ws_win CHAR(1),
    r INTEGER,
    ab INTEGER,
    h INTEGER,
    doubles INTEGER,
    triples INTEGER,
    hr INTEGER,
    bb INTEGER,
    so INTEGER,
    sb INTEGER,
    cs INTEGER,
    hbp INTEGER,
    sf INTEGER,
    ra INTEGER,
    er INTEGER,
    era NUMERIC(5,2),
    cg INTEGER,
    sho INTEGER,
    sv INTEGER,
    ip_outs INTEGER,
    ha INTEGER,
    hra INTEGER,
    bba INTEGER,
    soa INTEGER,
    e INTEGER,
    dp INTEGER,
    fp NUMERIC(5,3),
    name VARCHAR(100),
    park VARCHAR(100),
    attendance INTEGER,
    bpf INTEGER,
    ppf INTEGER,
    team_id_br VARCHAR(10),
    team_id_lahman45 VARCHAR(10),
    team_id_retro VARCHAR(10),
    PRIMARY KEY (year_id, team_id)
);