package com.owengc.baseball_ai.config;

import com.zaxxer.hikari.HikariDataSource;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.jdbc.autoconfigure.DataSourceProperties;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;

@Configuration
public class DataSourceConfig {

    /** Queries generated by the LLM are capped at this many milliseconds. */
    private static final String READONLY_INIT_SQL = "SET statement_timeout = 5000";

    @Bean
    @Primary
    @ConfigurationProperties("spring.datasource")
    public DataSourceProperties primaryDataSourceProperties() {
        return new DataSourceProperties();
    }

    @Bean
    @Primary
    public DataSource dataSource(
            @Qualifier("primaryDataSourceProperties") DataSourceProperties props) {
        return props.initializeDataSourceBuilder()
                .type(HikariDataSource.class)
                .build();
    }

    @Bean
    @ConfigurationProperties("readonly.datasource")
    public DataSourceProperties readonlyDataSourceProperties() {
        return new DataSourceProperties();
    }

    @Bean
    public DataSource readonlyDataSource(
            @Qualifier("readonlyDataSourceProperties") DataSourceProperties props) {
        HikariDataSource dataSource = props.initializeDataSourceBuilder()
                .type(HikariDataSource.class)
                .build();
        dataSource.setConnectionInitSql(READONLY_INIT_SQL);
        return dataSource;
    }

    @Bean
    public JdbcTemplate readonlyJdbcTemplate(
            @Qualifier("readonlyDataSource") DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }
}